# Site settings
name: 泉哥笔记
email: 402059985@QQ.COM
author: XQ
url: https://imxingquan.github.io/
resume_site: https://imxingquan.github.io/
github: https://github.com/imxingquan/
baseurl: ""
description: (+ 1 2 3)
meta_description: 泉哥的个人博客
motto: 
banner: dfd

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: imxignquan

# Build settings
markdown: kramdown

baidu_analysis: 

